---
- hosts: all 
  become: true 
  tasks:
  - name: Install Apache on Debian/Ubuntu
    apt:
      name: 'apache2'
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  - name: Install Apache on CentOS
    yum:
      name: 'httpd'
      state: latest
    when: ansible_distribution == "CentOS"
  - name: enable httpd service
    service:
      enabled: true
      state: started

